version: "3"
services:
  postgres:
    image: "postgres"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres:/var/lib/postgresql/data
  turbo-carnival:
    build:
      context: ./
    image: "turbo-carnival:1.0"
    volumes:
      - ./cmd/config.yaml:/opt/config.yaml:ro
    ports:
      - "1010:1010"
    depends_on:
      - postgres
volumes:
  postgres: